aws_access_key = "AKIAJ2SZL57UXC6QX4OQ"
aws_secret_key = "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"
aws_region = "us-east-1"
vpc_cidr = "10.0.0.1/16"
public_subnet1_cidr = "10.0.0.1/24"
public_subnet2_cidr = "10.0.0.2/24"
public_subnet3_cidr = "10.0.0.3/24"
private_subnet_cidr = "10.0.0.4/24"
vpc_name = "terraform_aws_tet"
IGW_name "terraform_igw_name"
public_subnet1_name = "terraform_pub_subnet1"
public_subnet2_name = "terraform_pub_subnet2"
public_subnet3_name = "terraform_pub_subnet3"
private_subnet_name = "terraform_pr_subnet"
main_ROuting_table =terraform_main_table_testing"
key_name = "inter"
environment = "dev"
